[package]
name = "Rust101"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4.1"
bytes = "1.11.0"
csv = "1.4.0"
actix-web = "4.12.0"
[dev-dependencies]
reqwest = "0.12.24"
